version: '3.6'
services: 
    notifications_api:
        build: .\stocks_api
        container_name: notifications
        ports: 
            - 5001:5001
    # db:
    #     image: postgres:9.6
    #     container_name: janj
    #     restart: always
    #     environment:
    #         - POSTGRES_PASSWORD=JANJ
    #     ports:
    #         - 5432:5432
    #     volumes:
    #         - ./:/home/
    #         - ./../postgres-data:/var/lib/postgresql/data
